---
- name: Create a directory if it does not exist
  file:
    path: "{{ compiled_conf_files_path }}"
    state: directory
    mode: '0750'

- name: Prepare php-fpm www pool conffile
  template:
    src: "templates/php-fpm.conf.j2"
    dest: "{{ compiled_conf_files_path }}/php-fpm.conf"
    mode: "u=r,g=r"